config/routes.rb
Rails.application.routes.draw do
  resources :posts
end

app/models/post.rb
# coding: utf-8
class Post < ActiveRecord::Base

  # 前後のパスを取得する
  # http://easyramble.com/active-record-prev-next.html
  def previous
    Post.where("id < ?", self.id).order("id DESC").first
  end
  
  def next
    Post.where("id > ?", self.id).order("id ASC").first
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
# coding: utf-8
class PostsController < ApplicationController
  # 投稿一覧
  def index
    # Postテーブルからすべて検索
    @posts = Post.all
  end

  # 新規投稿作成
  def create
    @post = Post.new
    @post.content = params[:post][:content]
    @post.author =  params[:post][:author]
    @post.save
    
    # 投稿一覧へリダイレクト
    redirect_to "/posts"
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meigen100</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>努力の名言50</h1>
<div id="grid-content">
  <% @posts.each do |post| %>
    <%= link_to(post_path(post.id)) do %>
    <div>
    <h3><%= post.content %></h3>
    <p><%= post.author %></p>
    </div>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= form_for Post.new do |f| %>
  <%= f.label :content%> </br>
  <%= f.text_area :content %>
  <p></p>
  <%= f.label :author %> </br>
  <%= f.text_field :author %>
  <p></p>  
  <%= f.submit '投稿'%>
<% end %>

app/views/posts/show.html.erb
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<h3><%= @post.content %></h3>
<p><%= @post.author %></p>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<ul class="pager">
  <li><% unless @post.previous.nil? %>
    <%= link_to 'Prev', post_path(@post.previous) %> 
  <% end %></li>
  <li><%= link_to 'Top', posts_path, method: :get %></li>
  <li><% unless @post.next.nil? %>
    <%= link_to 'Next', post_path(@post.next) %>
  <% end %></li>
</ul>